### ISSUE TITLE
Add ElementAtOrDefault method and tests

### ISSUE THREAD

**Issue by jreina** [jreina/ShittyLINQ#33]
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.elementatordefault?view=netframework-4.7.2

**Comment by moolicc** [comment]
I'll implement this one, too!

**Comment by moolicc** [comment]
..or not lol

**Comment by CodingNagger** [comment]
Sorry @IcecreamBurglar , forgot to mark it just implemented.

**Comment by moolicc** [comment]
All good, no worries.
