### ISSUE TITLE
Add Except method and tests

### ISSUE THREAD

**Issue by jreina** [jreina/ShittyLINQ#35]
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.except?view=netframework-4.7.2

**Comment by moolicc** [comment]
I think I can take a crack at this. Should have a PR submitted shortly, standby.

**Comment by moolicc** [comment]
Btw, I might try to do some of the others as well. Would you like them in one PR, or separated and organized across multiple PRs?

**Comment by jreina** [comment]
One method per PR, please. They are much easier to review that way. Plus you get more Hacktoberfest credit 🙂 Thanks!

**Comment by moolicc** [comment]
Sounds good to me!
No problem!
